# This is a basic workflow to help you get started with Actions

name: Java CI with Maven

env :
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
 # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name : Set up JDK 18
        uses : actions/setup-java@v3
        with :
          java-version : '18'
          distribution : 'temurin'
          cache : maven
          
      - name : Build with Maven
        run : mvn -B package --file pom.xml
      - name: SonarCloud Scan
        run: mvn -B verify sonar:sonar
      - name: Check Javadoc
        run: mvn javadoc:javadoc --file pom.xml
      - name: Check Licences
        run: mvn apache-rat:check --file pom.xml


#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
